version: '3.3'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    env_file:
      - .env

  pgdb:
    image: postgres:13
    container_name: pgdb
    environment:
      - POSTGRES_DB=Agrigate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=pgdb
      - POSTGRES_PORT=5432
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      depends_on:
        - pgdb
      environment:
        - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=ubuntu
        - PGADMIN_LISTEN_PORT=5050
      restart: always
      ports:
        - 5050:5050

volumes:
    django:
    pgdb: