version: '3.3'

services:
  pgdb:
    restart: always
    image: postgres:latest
    container_name: pgdb
    environment:
      - POSTGRES_DB=Agrigate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
      restart: always
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      depends_on:
        - pgdb
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: ubuntu     
      ports:
        - "80:80"

  django:
    build: .
    restart: always
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    env_file:
      - .env

volumes:
    django:
    pgdb: