version: '3.3'

services:
  django:
    build: .
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb
    env_file:
      - .env

  pgdb:
    image: postgres:11
    container_name: pgdb
    environment:
      - POSTGRES_DB=Agrigate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5010:5432

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: pgadmin
      depends_on:
        - pgdb
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: ubuntu
        PGADMIN_LISTEN_PORT: 80      
      ports:
        - 8080:80
      restart: always

volumes:
    django:
    pgdb: