# Generated by Django 4.1.5 on 2023-08-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_kk',
        ),
        migrations.RemoveField(
            model_name='usefulcatalog',
            name='chat_id',
        ),
    ]
