# Generated by Django 4.2.4 on 2023-09-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_telegramgroupchannel_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsuser',
            name='user_link',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
