# Generated by Django 4.1.5 on 2023-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='message_id',
            field=models.BigIntegerField(),
        ),
    ]
