# Generated by Django 4.1.5 on 2023-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_chat_id_user_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foobar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.CharField(max_length=200)),
            ],
        ),
    ]
