# Generated by Django 4.2.4 on 2023-09-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_adsuser_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulcatalog',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='useful_catalogs', to='shop.usefulcategory'),
        ),
    ]
