# Generated by Django 4.1.5 on 2023-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupchannel',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usefulcatalog',
            name='link',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
