# Generated by Django 4.1.5 on 2023-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group_id',
            field=models.BigIntegerField(),
        ),
    ]
