# Generated by Django 4.1.5 on 2023-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Passive'), ('-1', 'Deleted')], default='1', max_length=10),
        ),
    ]
