# Generated by Django 4.1.5 on 2023-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_telegramgroupchannel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuser',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
