# Generated by Django 4.1.5 on 2023-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_foobar_foo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.JSONField(blank=True),
        ),
    ]
