# Generated by Django 4.1.5 on 2023-08-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroupchannel',
            name='type',
            field=models.CharField(choices=[('Group', 'Group'), ('Channel', 'Channel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usefulcatalog',
            name='type',
            field=models.CharField(choices=[('Bot', 'Bot'), ('Group', 'Group'), ('Channel', 'Channel'), ('Website', 'Website')], max_length=20),
        ),
    ]
