# Generated by Django 4.1.5 on 2023-05-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='datatime',
            new_name='timestep',
        ),
    ]
