# Generated by Django 4.1.5 on 2023-03-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_user',
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_list', to='shop.category'),
        ),
        migrations.DeleteModel(
            name='ProductUser',
        ),
    ]
