# Generated by Django 4.1.5 on 2023-02-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_keywords_delete_foobar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_words', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='keywords',
            name='key_words',
            field=models.JSONField(),
        ),
    ]
