# Generated by Django 4.1.5 on 2023-03-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to='shop.productuser'),
        ),
    ]
