# Generated by Django 4.1.5 on 2023-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_group_options_product_group_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='group_id',
            new_name='group_old_id',
        ),
    ]
