# Generated by Django 4.1.5 on 2023-02-03 10:55

from django.db import migrations
import jsonfield.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
