# Generated by Django 4.1.5 on 2023-05-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_group_test_product_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='group_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='group_old_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestep',
        ),
    ]
