name: Second Server Deploy

# on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: 3.226.69.133
        USERNAME: ubuntu
        key: ${{ secrets.NEW_KEY }}
        PORT: 22
        script: |
          cd ~
          cd Marcketplace-Agrigate_bot
          git pull origin main
          
          sudo docker-compose down
          sudo docker-compose build
          sudo docker-compose up
      
      